theme: jekyll-theme-hacker
# 网站标题 (会显示在页面顶端)
title: ONLY THE LIMIT

# 网站描述 (会显示在标题下方)
description: 4173RN473R IS WATCHING YOU =D

# 是否显示 "Download .zip" 和 "Download .tar.gz" 的下载按钮
# 可选值为 true 或 false
show_downloads: false

# 这个设置用于首页展示博客列表
paginate: 5
paginate_path: "/blog/page:num/"

# 关键配置：设置网站根目录为 /4173RN473R/
baseurl: "/4173RN473R"

# 你的网站最终地址。建议加上，但 baseurl 是关键的
url: "https://14capacitors.github.io"

